# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            wishyouhappy
paginate:         1
baseurl:          /
author:
  name:           wishyouhappy

pages_list:       
  About: '/about'
  Blogs: '/blogs'
  Photo: '/photos'
  Gallary: '/gallary'

code_dir: source/downloads/code




