# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            wishyouhappy
url: http:
paginate:         1
baseurl:          /
author:
  name:           wishyouhappy

pages_list:       
  About: '/about'
  Blogs: '/blogs'
  Photo: '/photos'
  Painting: '/painting'

code_dir: source/downloads/code




