# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://blog.wish.com
paginate:         1
baseurl:          /
author:
  name:           wishyouhappy

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'




